---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
First you load the data from the package

```{r example}
library(mladv)
data(SSI_data)
head(SSI_data,3)
```

With the data_set, we can convert the raw market data into different bars such as time bars or volume bars as examples below with `SSI_data`

```{r volumebarr}
volume6000 <- volumebarr(SSI_data, 15000)
head(volume6000)
```

```{r timebar}
minute_bar <- timebar(SSI_data, "minute")
head(minute_bar)
```

We can still use functions from popular packages such as `quantmod` or `ggplot2` with the return data.frame 

```{r fig2}
library(xts)
library(quantmod)
minute_plot <- xts(minute_bar[,2:6], order.by=minute_bar$Date)
```

```{r, fig.width = 7}
candleChart(minute_plot, theme="white", multi.col=T, name="Minute bar chart")
```

> "He who gives up [code] safety for [code] speed deserves neither."
([via](https://twitter.com/hadleywickham/status/504368538874703872))
