# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiply by 2
#'
#' @param x A single integer
#' @export
timesTwo <- function(x) {
    .Call(`_mladv_timesTwo`, x)
}

#' data
#'
#' @param DataFrame data
#' @param Integer volume
#'
#' @export
volumebarc <- function(data, Vol) {
    .Call(`_mladv_volumebarc`, data, Vol)
}

